# This is a basic workflow to help you get started with Actions

name: PHP

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run-cs:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php-version: [7.4, php-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: PHP Version
        run: |
          echo -n Default version:,
          which php && php -v,
          echo -n Direct version:,
          /usr/bin/php${{ matrix.php-version }} -v
      - name: Print PHP ${{ matrix.php-version }} Info
        run: php -i

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
